name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <aws-region> # Replace with your desired AWS region

      - name: Install and configure Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y
          sudo usermod -aG docker $USER

      - name: Build and push Docker images
        run: |
          docker build -t <image-name> .
          docker tag <image-name>:latest <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<image-name>:latest
          docker push <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<image-name>:latest

      - name: Connect to EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: <ec2-instance-ip>
          username: <ec2-instance-username>
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 Instance
        run: |
          ssh <ec2-instance-username>@<ec2-instance-ip> 'docker pull <aws-account-id>.dkr.ecr.<aws-region>.amazonaws.com/<image-name>:latest'
          ssh <ec2-instance-username>@<ec2-instance-ip> 'docker stop <container-name>'
